### ISSUE TITLE
(Fixed in Hg) Kedr fails to build on kernel 3.4.0-rc2

### ISSUE THREAD

**Issue by euspectre** [euspectre/kedr#6]
Original [issue 6](https://code.google.com/p/kedr/issues/detail?id=6) created by euspectre on 2012-04-16T11:54:15.000Z:

When buildin Kedr from repository on kernel 3.4.0-rc2, compilation fails with:

/home/winnukem/kedr/build/core/arch/x86/lib/inat.c:32:13: error: conflicting types for ‘inat_get_escape_attribute’
/usr/src/packages/BUILD/kernel-3.4.0_rc2_gcov/arch/x86/include/asm/inat.h:101:20: note: previous declaration of ‘inat_get_escape_attribute’ was here
/home/winnukem/kedr/build/core/arch/x86/lib/inat.c:55:13: error: conflicting types for ‘inat_get_group_attribute’
/usr/src/packages/BUILD/kernel-3.4.0_rc2_gcov/arch/x86/include/asm/inat.h:104:20: note: previous declaration of ‘inat_get_group_attribute’ was here
make[4]: **\* [/home/winnukem/kedr/build/core/arch/x86/lib/inat.o] Error 1
make[3]: **\* [_module_/home/winnukem/kedr/build/core] Error 2
make[2]: **\* [core/kedr.ko] Error 2
make[1]: **\* [core/CMakeFiles/kedr.dir/all] Error 2
make: **\* [all] Error 2

After changing the inat_get_escape_attribute and inat_get_group_attribute declarations to

insn_attr_t inat_get_escape_attribute(insn_byte_t opcode, int last_pfx, insn_attr_t esc_attr)
insn_attr_t inat_get_group_attribute(insn_byte_t modrm, int last_pfx, insn_attr_t grp_attr),

compilation still fails with

/home/winnukem/kedr/build/core/arch/x86/lib/insn.c: In function ‘insn_get_opcode’:
/home/winnukem/kedr/build/core/arch/x86/lib/insn.c:204:3: error: implicit declaration of function ‘insn_last_prefix’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[4]: **\* [/home/winnukem/kedr/build/core/arch/x86/lib/insn.o] Error 1
make[3]: **\* [_module_/home/winnukem/kedr/build/core] Error 2
make[2]: **\* [core/kedr.ko] Error 2
make[1]: **\* [core/CMakeFiles/kedr.dir/all] Error 2
make: **\* [all] Error 2

After changing insn_get_opcode calls to insn_get_opcode_id, compilation fails like in http://code.google.com/p/kedr/issues/detail?id=5
